// front_end-frameworks/svelte/src/components/sections/Features.svelte
<script>
  import features from "../../data/features.js";
  import FeatureCard from "../cards/FeatureCard.svelte";
  import SectionBadge from "../ui/SectionBadge.svelte";
  import SectionTitle from "../ui/SectionTitle.svelte";
</script>

<section id="features-section" class="bg-black py-24">
  <div class="mx-auto max-w-6xl px-6">
    <div class="flex flex-col items-center gap-4 pb-10">
      <SectionBadge>✦ Features ✦</SectionBadge>
      <SectionTitle
        line1="Everything You Need to Build"
        line2="With powerful AI agents"
      />
    </div>
    <div class="grid gap-8 md:grid-cols-3">
      {#each features as feature, index (index)}
        <FeatureCard
          icon={feature.icon}
          title={feature.title}
          description={feature.description}
        />
      {/each}
    </div>
  </div>
</section>

// front_end-frameworks/react/src/components/sections/Features.jsx
import features from "../../data/features";
import FeatureCard from "../cards/FeatureCard";
import SectionBadge from "../ui/SectionBadge";
import SectionTitle from "../ui/SectionTitle";

function Features() {
  return (
    <section id="features-section" className="bg-black py-24">
      <div className="mx-auto max-w-6xl px-6">
        <div className="flex flex-col items-center gap-4 pb-10">
          {/* Eyebrow */}
          <SectionBadge>✦ Features ✦</SectionBadge>

          {/* Title */}
          <SectionTitle
            line1="Everything You Need to Build"
            line2="With powerful AI agents"
          />
        </div>

        {/* Features grid */}
        <div className="grid gap-8 md:grid-cols-3">
          {features.map((feature, index) => {
            return (
              <FeatureCard
                key={index}
                icon={feature.icon}
                title={feature.title}
                description={feature.description}
              />
            );
          })}
        </div>
      </div>
    </section>
  );
}

export default Features;
