// front_end-frameworks/vue/src/components/layout/Header.vue
<script setup>
import Brand from "../ui/Brand.vue";
import Button from "../ui/Button.vue";
</script>

<template>
  <header class="fixed top-0 right-0 left-0 z-50 bg-slate-950">
    <div class="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
      <a href="#">
        <Brand />
      </a>

      <div class="flex items-center gap-6">
        <nav class="hidden gap-6 text-sm text-slate-500 md:flex">
          <a href="#about-section">About</a>
          <a href="#features-section">Features</a>
          <a href="#insights-section">Insights</a>
          <a href="#contact-section">Contact</a>
        </nav>

        <Button href="#">Enroll now</Button>
      </div>
    </div>
  </header>
</template>

// front_end-frameworks/react/src/components/Header.jsx
import { BrainCircuit } from 'lucide-react';

function Header() {
  return (
    <header className="bg-slate-950 fixed top-0 left-0 right-0">
      <div className="flex justify-between items-center max-w-6xl mx-auto px-6 py-4">

        {/* Logo + Titre */}
        <a className="flex items-center gap-2" href="#">
          <div className="bg-violet-500 text-slate-50 rounded-lg shadow-lg shadow-violet-500/40 p-2">
            <BrainCircuit />
          </div>
          <span className="text-slate-50">Agentic AI</span>
        </a>

        {/* Navbar */}
        <div className="flex items-center gap-6">
          <nav className="gap-6 text-slate-500 hidden md:flex">
            <a href="#about-section">About</a>
            <a href="#features-section">Features</a>
            <a href="#insights-section">Insights</a>
            <a href="#contact-section">Contact</a>
          </nav>

        {/* CTA */}
          <a className="px-4 py-2 font-semibold rounded-md bg-violet-500 hover:bg-violet-600 shadow-lg shadow-violet-500/40 text-slate-50" href="#">Enroll now</a>
        </div>
      </div>
    </header>
  );
}

export default Header;
