// front_end-frameworks/svelte/src/App.svelte
<script>
  import Footer from "./components/layout/Footer.svelte";
  import Header from "./components/layout/Header.svelte";
  import About from "./components/sections/About.svelte";
  import Contact from "./components/sections/Contact.svelte";
  import Features from "./components/sections/Features.svelte";
  import Hero from "./components/sections/Hero.svelte";
  import Insights from "./components/sections/Insights.svelte";
</script>

<div class="min-h-screen bg-slate-950">
  <Header />
  <main>
    <Hero />
    <About />
    <Features />
    <Insights />
    <Contact />
  </main>
  <Footer />
</div>

// front_end-frameworks/react/src/App.jsx
import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";
import About from "./components/sections/About";
import Contact from "./components/sections/Contact";
import Features from "./components/sections/Features";
import Hero from "./components/sections/Hero";
import Insights from "./components/sections/Insights";

function App() {
  return (
    <div className="min-h-screen bg-slate-950"> {/* min-h-screen = Fond global de la page */}
      <Header />
      <main>
        <Hero />
        <About />
        <Features />
        <Insights />
        <Contact />
      </main>
      <Footer />
    </div>
  );
}

export default App;
