// front_end-frameworks/svelte/src/App.svelte
<script>
  import { Sparkles } from '@lucide/svelte'
</script>

<div class="min-h-screen flex flex-col items-center justify-center gap-4 bg-slate-950 text-white">
  <Sparkles class="w-10 h-10 text-violet-500" />
  <h1 class="text-4xl font-bold">Agentic AI</h1>
  <h2 class="text-lg text-slate-400">Svelte project setup</h2>
</div>

// front_end-frameworks/vue/src/App.vue
<script setup>
import { Bot } from "@lucide/vue";
</script>

<template>
  <main
    class="flex flex-col items-center justify-center min-h-screen gap-4 bg-slate-950 text-white"
  >
    <Bot class="w-12 h-12 text-purple-400" />
    <h1 class="text-4xl font-bold">Agentic AI</h1>
    <h2 class="text-lg text-slate-400">Vue.js project setup</h2>
  </main>
</template>
