// front_end-frameworks/react/src/sections/Hero.jsx
import { ArrowRight } from "lucide-react";

/* Stats table for .map()*/
const stats = [
  { value: "10K+", label: "Active agents" },
  { value: "99.9%", label: "Uptime" },
  { value: "50M+", label: "Tasks automated" },
  { value: "24/7", label: "Support" },
];

function Hero() {
  return (
    <section
      id="hero-section"
      className="flex flex-col items-center gap-8 pt-36 pb-24 text-center"
    >
      {/* Eyebrow */}
      <p className="rounded-full border border-violet-500/20 bg-violet-500/10 px-4 py-2 text-xs text-violet-300">
        ♦ The future of coding ♦
      </p>

      {/* Title */}
      <h1 className="text-5xl leading-none font-black tracking-tight md:text-7xl">
        <span className="text-slate-50">Build smarter workflows</span>
        <br />
        <span className="text-violet-300">with Agentic AI</span>
      </h1>

      {/* Description */}
      <p className="max-w-2xl text-sm text-slate-300 md:text-base">
        Create autonomous AI agents that think, plan, and execute complex tasks.
        Transform your business with intelligent automation.
      </p>

      {/* CTA */}
      <div className="flex flex-col gap-4 py-10 md:flex-row">
        <a
          className="inline-flex items-center gap-2 rounded-md bg-violet-500 px-4 py-2 font-semibold text-slate-50 shadow-lg shadow-violet-500/40 hover:bg-violet-600"
          href="#"
        >
          Start learning with Holberton School <ArrowRight />
        </a>
        <a
          className="rounded-md border border-slate-800 bg-slate-950 px-4 py-2 font-semibold text-slate-50 hover:bg-slate-900"
          href="#"
        >
          Methodology
        </a>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 gap-8 md:grid-cols-4">
        {stats.map((stat) => {
          return (
            <div
              key={stat.label}
              className="rounded-xl border border-slate-800 bg-slate-950 p-6 shadow-xl shadow-slate-950/40"
            >
              <p className="text-4xl font-black text-violet-300">
                {stat.value}
              </p>
              <p className="text-slate-500">{stat.label}</p>
            </div>
          );
        })}
      </div>
    </section>
  );
}

export default Hero;

// front_end-frameworks/svelte/src/components/sections/Hero.svelte
<script>
  import { ArrowRight } from "@lucide/svelte";
  import SectionBadge from "../ui/SectionBadge.svelte";
  import Button from "../ui/Button.svelte";
  import StatCard from "../cards/StatCard.svelte";

  const stats = [
    { value: "10K+", label: "Active agents" },
    { value: "99.9%", label: "Uptime" },
    { value: "50M+", label: "Tasks automated" },
    { value: "24/7", label: "Support" },
  ];
</script>

<section
  id="hero-section"
  class="relative isolate flex flex-col items-center gap-8 overflow-hidden border-b border-slate-800 pt-36 pb-24 text-center"
>
  <div
    class="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(ellipse_70%_60%_at_15%_10%,rgba(139,92,246,0.35),transparent),radial-gradient(ellipse_70%_60%_at_85%_90%,rgba(59,130,246,0.25),transparent)]"
  ></div>
  <div
    class="pointer-events-none absolute inset-0 -z-10 bg-[linear-gradient(to_right,rgba(148,163,184,0.12)_1px,transparent_1px),linear-gradient(to_bottom,rgba(148,163,184,0.12)_1px,transparent_1px)] bg-size-[72px_72px] opacity-30"
  ></div>
  <div
    class="pointer-events-none absolute inset-x-0 bottom-0 -z-10 h-32 bg-linear-to-b from-transparent to-black"
  ></div>

  <SectionBadge>✦ The future of coding ✦</SectionBadge>

  <h1 class="text-5xl leading-none font-black tracking-tight md:text-7xl">
    <span class="text-slate-50">Build smarter workflows</span><br /><span
      class="text-violet-300">with Agentic AI</span
    >
  </h1>

  <p class="max-w-2xl text-sm text-slate-300 md:text-base">
    Create autonomous AI agents that think, plan, and execute complex tasks.
    Transform your business with intelligent automation.
  </p>

  <div class="flex flex-col items-center gap-4 py-10 md:flex-row">
    <Button href="#">Start learning with Holberton School <ArrowRight /></Button
    >
    <Button variant="secondary" href="#">Methodology</Button>
  </div>

  <div class="grid grid-cols-2 gap-8 md:grid-cols-4">
    {#each stats as stat (stat.label)}
      <StatCard value={stat.value} label={stat.label} />
    {/each}
  </div>
</section>
